query allArticles {
  articles {
    data {
      id
      attributes {
        title
        content
        categories {
          data {
            id
            attributes {
              name
            }
          }
        }
        image {
          data {
            id
            attributes {
              url
            }
          }
        }
      }
    }
  }
}